name: kanjibox

services:
  db:
    image: postgres:latest
    container_name: kanjibox-back-db
    environment:
      POSTGRES_DB: kanji
      POSTGRES_USER: kanji
      POSTGRES_PASSWORD: kanji
    ports:
      - "5432:5432"
    networks:
      - kanji_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      target: development
    container_name: kanjibox-back-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - kanji_network
    volumes:
      - api_data:/app/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kanji
      SPRING_DATASOURCE_USERNAME: kanji
      SPRING_DATASOURCE_PASSWORD: kanji
      AUTO_TRANSLATION_ENABLED: false
      GOOGLE_API_KEY:
      OKTA_OAUTH2_AUDIENCE:
      OKTA_OAUTH2_ISSUER:

  front:
    image: fbrtd/kanjibox-front:latest
    container_name: kanjibox-front
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - kanji_network
    volumes:
      - front_data:/app/data
    environment:
      BACKEND_API_URL: http://api:8080/kanjibox

networks:
  kanji_network:
    driver: bridge

volumes:
  postgres_data:
  api_data:
  front_data:
