version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: kanjibox-db
    environment:
      POSTGRES_DB: kanji
      POSTGRES_USER: kanji
      POSTGRES_PASSWORD: kanji
    ports:
      - "5432:5432"
    networks:
      - kanji_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      target: development
    container_name: kanjibox-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - kanji_network
    volumes:
      - app_data:/app/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kanji
      SPRING_DATASOURCE_USERNAME: kanji
      SPRING_DATASOURCE_PASSWORD: kanji

networks:
  kanji_network:
    driver: bridge

volumes:
  postgres_data:
  app_data:
