# ===============================
#=LOCAL
# ===============================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kanjidb
    username: postgres
    password: root
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
kanji:
  cors:
    allowed-origins: "http://localhost:3000"
  translation:
    auto:
      enable: false
okta:
  oauth2:
    audience: https://kanjibox/api
    issuer: https://dev-62s0gk167wgszh7o.jp.auth0.com/