spring:
  datasource:
    continue-on-error: true
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: file:./db/insert_data.sql

# Disable translation
kanji:
  translation:
    deepl:
      api-key: fake-key
    auto:
      enable: false
    timeout-seconds: 5
  rate-limit:
    capacity: 30
    refill-per-minute: 20