spring:
  datasource:
    continue-on-error: true
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: file:./db/insert_data.sql

# Disable translation
kanji:
  translation:
    auto:
      enable: false
okta:
  oauth2:
    audience: https://kanjibox/api
    issuer: https://dev-62s0gk167wgszh7o.jp.auth0.com/